python_library(
  name = 'compactor',
  sources = globs('*.py'),
  dependencies = [
    python_requirement('trollius'),  # 2.x asyncio
    python_requirement('tornado'),
    python_requirement('twitter.common.lang'),
  ]
)
